OKEXSPOT = "OKEXSPOT"
OKEXFUTURES = "OKEXFUTURES"
OKEXSWAP = "OKEXSWAP"
HUOBISPOT = 'HUOBISPOT'
HUOBIFUTURES = 'HUOBIFUTURES'
HUOBISWAP = 'HUOBISWAP'
HUOBIUSDSWAP = 'HUOBIUSDSWAP'
HUOBIUSDTSWAP = 'HUOBIUSDTSWAP'
BINANCESPOT = "BINANCESPOT"
BINANCEFUTURES = "BINANCEFUTURES"
BINANCESWAP = 'BINANCESWAP'


BUY = "BUY"
SELL = "SELL"
BUYTOCOVER = "BUYTOCOVER"
SELLSHORT = "SELLSHORT"

LIMIT = "LIMIT"
MARKET = "MARKET"

NONE = "NONE"
SUBMITTED = "SUBMITTED"
PARTIAL_FILLED = "PARTIAL_FILLED"
FILLED = "FILLED"
CANCELED = "CANCELED"
FAILED = "FAILED"
CANCELLING = "CANCELLING"